//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SkeletonEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SKELETTYPE                  129
#define IDD_SELECTFILE                  130
#define IDD_EDITANIMATION               131
#define IDD_ACTIONPROP                  132
#define IDD_OPTION                      134
#define IDD_EXPORTSKINMODEL             135
#define IDD_EDITHOOK                    137
#define IDD_EDITAABB                    138
#define IDD_ADDHANGER                   139
#define IDD_MODELINFO                   140
#define IDD_GROUPACTION                 141
#define IDD_DIALOG1                     142
#define IDD_MODELPROP                   142
#define IDD_MERGESKELETON               144
#define IDD_ACTIONCOMBO                 145
#define IDD_ADDSKIN                     146
#define IDD_SUPPLETEST                  147
#define IDI_WARNINGICON                 149
#define IDD_SCALEBONE                   150
#define IDC_TREE_DIRECTORY              1000
#define IDC_LIST_FILE                   1001
#define IDC_STATIC_PROMPT               1002
#define IDC_LIST_JOINT                  1003
#define IDC_LIST_ACTION                 1004
#define IDC_BTN_DELACTION               1005
#define IDC_BTN_ADDACTION               1006
#define IDC_BTN_PLAYACTION              1007
#define IDC_BTN_REMOVEACTION            1007
#define IDC_STATIC_FRAMEAREA            1008
#define IDC_BTN_ADDSKELETON             1008
#define IDC_BTN_RESETJOINT              1009
#define IDC_BTN_STOPACTION              1010
#define IDC_BTN_ACTIONPROP              1011
#define IDC_BTN_PLAYSTEP                1011
#define IDC_EDIT_NAME                   1012
#define IDC_BTN_SELECTALL               1012
#define IDC_BTN_UNSELECTALL             1013
#define IDC_BTN_REVERSESELECT           1014
#define IDC_EDIT_BOXSIZE                1014
#define IDC_EDIT_STAFFRADIUS            1015
#define IDC_BTN_DELSKELETON             1015
#define IDC_BTN_EXPORTCHANNEL           1015
#define IDC_COMBO_CAMERAMOVESPEED       1016
#define IDC_BTN_MOVEUP                  1016
#define IDC_BTN_ABSTRACK                1016
#define IDC_LIST_SKELETON               1017
#define IDC_BTN_GROUPPLAY               1017
#define IDC_COMBO_CAMERAROTSPEED        1017
#define IDC_BTN_MOVEDOWN                1018
#define IDC_RADIO1                      1018
#define IDC_COMBO_MOUSEDRAGSPEED        1018
#define IDC_BTN_RELOADSKELETON          1019
#define IDC_RADIO2                      1019
#define IDC_BTN_JUMPTONEXT              1019
#define IDC_EDIT_SKELETONFILE           1020
#define IDC_BTN_ACTIONGROUP             1020
#define IDC_BTN_BROWSESKELETON          1021
#define IDC_CHECK_GENSKINMODEL          1022
#define IDC_EDIT_SKINMODELFILE          1023
#define IDC_CHECK_BINDSKIN              1024
#define IDC_EDIT_SKINFILE               1026
#define IDC_LIST_HOOKS                  1026
#define IDC_BTN_BROWSESKIN              1027
#define IDC_LIST_AABB                   1027
#define IDC_BTN_BROWSESKINMODEL         1028
#define IDC_EDIT_POSX                   1028
#define IDC_EDIT_POSY                   1029
#define IDC_EDIT_POSZ                   1030
#define IDC_SPIN_POSX                   1031
#define IDC_SPIN_POSY                   1032
#define IDC_SPIN_POSZ                   1033
#define IDC_EDIT_EXTX                   1034
#define IDC_EDIT_EXTY                   1035
#define IDC_EDIT_EXTZ                   1036
#define IDC_SPIN_EXTX                   1037
#define IDC_SPIN_EXTY                   1038
#define IDC_SPIN_EXTZ                   1039
#define IDC_BTN_SAVEBONEBOX             1040
#define IDC_LIST_HANGERS                1041
#define IDC_BTN_ADDHANGER               1042
#define IDC_BTN_DELETEHANGER            1043
#define IDC_BTN_TESTHANGER              1044
#define IDC_COMBO_HANGPOINTS            1045
#define IDC_BTN_STOPHANGER              1045
#define IDC_EDIT_FILENAME               1046
#define IDC_BTN_MODEL                   1049
#define IDC_BTN_GFX                     1050
#define IDC_EDIT_PROP                   1052
#define IDC_COMBO_CC                    1055
#define IDC_CHECK_MODELAABB             1056
#define IDC_BTN_SKINMODELFILE           1058
#define IDC_BTN_SKINFILE                1059
#define IDC_LIST_PROP                   1059
#define IDC_EDIT_PROPNAME               1060
#define IDC_EDIT_PROPVALUE              1061
#define IDC_BTN_SUBMIT                  1062
#define IDC_BTN_ADDPROP                 1063
#define IDC_BTN_DELPROP                 1064
#define IDC_BTN_UP                      1066
#define IDC_BTN_DOWN                    1067
#define IDC_BTN_TOP                     1068
#define IDC_BTN_BOTTOM                  1069
#define IDC_BTN_MERGE                   1071
#define IDC_COMBO_ACTION1               1073
#define IDC_COMBO_ACTION_A              1074
#define IDC_COMBO_ACTION2               1077
#define IDC_COMBO_ACTION3               1078
#define IDC_SLIDER_WEIGHT1              1079
#define IDC_SLIDER_WEIGHT2              1080
#define IDC_STATIC_WEIGHT1              1081
#define IDC_STATIC_WEIGHT2              1082
#define IDC_SLIDER_WEIGHT3              1083
#define IDC_STATIC_WEIGHT3              1084
#define IDC_BTN_PLAY                    1085
#define IDC_LIST_ACTIONCANDIDATE        1089
#define IDC_LIST_SKIN                   1090
#define IDC_BTN_ADDSKIN                 1091
#define IDC_BTN_REPLACESKIN             1092
#define IDC_BTN_REMOVESKIN              1093
#define IDC_BTN_DELETESKIN              1094
#define IDC_EDIT_WARNING                1095
#define IDC_LIST_SUPPLEMESH             1097
#define IDC_SPIN_X                      1101
#define IDC_EDIT_X                      1102
#define IDC_SPIN_Y                      1103
#define IDC_EDIT_Y                      1104
#define IDC_SPIN_Z                      1105
#define IDC_EDIT_Z                      1106
#define IDC_SPIN_LENGTH                 1107
#define IDC_EDIT_LENGTH                 1108
#define IDC_SPIN_RADIUS                 1109
#define IDC_EDIT_RADIUS                 1110
#define IDC_LIST_PHYSHAPE               1111
#define IDC_EDIT_COEFFICIENT            1112
#define IDC_EDIT_GRAVITY                1113
#define IDC_EDIT_AIRRESIST              1114
#define IDC_EDIT_VERTWEIGHT             1115
#define IDC_STATIC_WARNING              1116
#define IDC_LIST_BONES                  1118
#define IDC_BTN_RESTORE                 1119
#define IDC_STATIC_ANIMINFO             1120
#define IDC_BTN_IMPORTACTS              1121
#define IDC_BTN_EXPORTACTS              1122
#define IDC_EDIT_ACTFILE                1123
#define IDC_BTN_BROWSE                  1124
#define IDC_CHECK_ADDACTION             1125
#define IDC_CHECK_ENABLEUPDATEACT       1126
#define IDC_CHECK_OVERWRITE             1129
#define IDC_EDIT_LOOPNUM                1130
#define IDC_CHECK_ENABLECHANNEL         1131
#define IDC_EDIT_TRACKFILE              1136
#define IDC_SLIDER_PLAYSTEP             1138
#define IDC_EDIT_CURFRAME               1140
#define IDC_CHECK_USEABSTRACK           1142
#define IDC_EDIT_TRACKDIR               1143
#define ID_EDIT_CHANGESKELETON          32771
#define ID_FILE_SETWORKDIR              32772
#define ID_VIEW_EDITACTIONWND           32773
#define ID_EDIT_OPTION                  32775
#define ID_EDIT_CHANGESKIN              32776
#define ID_VIEW_SETCAMERAPOS            32777
#define ID_VIEW_SKELETONONLY            32778
#define ID_FILE_EXPORTSKINMODEL         32780
#define ID_VIEW_EDITHOOKWND             32783
#define ID_VIEW_EDITAABBWND             32785
#define ID_BUTTON32787                  32787
#define ID_EDIT_REMOVESKIN              32788
#define ID_VIEW_MODELINFO               32789
#define ID_EDIT_MODELPROP               32790
#define ID_VIEW_PHYSIQUESHAPE           32791
#define ID_EDIT_MERGESKELETON           32794
#define ID_VIEW_BOUNDBOX                32795
#define ID_EDIT_ADDPHYSIQUE             32798
#define ID_EDIT_REMOVEPHYSIQUE          32799
#define ID_VIEW_BONECOORD               32801
#define ID_VIEW_GROUND                  32801
#define ID_FILE_CLOSEDOC                32802
#define ID_EDIT_ACTFACTORY              32803
#define ID_VIEW_NORMAL                  32805
#define ID_VIEW_SHOW                    32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
